### ISSUE TITLE
PagedFile init spamming

### ISSUE THREAD

**Issue by richgal** [dominicletz/dets_plus#2]
I realised that many PagedFile init processes got spawned and stayed hibernated in case the DetsPlus.close is called. These processes don't terminate themselfs. 

Since I'm not calling DetsPlus.close the issues dissapeared. 

Is this a normal behavior for this Module? 

![image](https://user-images.githubusercontent.com/15719792/197180209-4eff6ed1-65ca-4ff6-ae4f-6dab0d1d64b4.png)

**Comment by richgal** [comment]
But PageFile got spawned every time DetsPlus.lookup called also

**Comment by dominicletz** [comment]
That looks like a bug indeed.

**Comment by dominicletz** [comment]
Fixed in commit 9909416 and released under v2.1.3
